version: '3.7'
services:
  jenkins:
    build:
      context: '.'
    container_name: 'jenkins'
    hostname: jenkins
    privileged: true
    restart: 'always'
    expose:
      - '50000'
      - '8080'
    volumes:
      - '../../docker/jenkins/:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
  nginx:
    image: 'nginx:latest'
    container_name: 'nginx'
    hostname: nginx
    restart: 'always'
    depends_on:
      - 'jenkins'
    ports:
      - '80:80'
    volumes:
      - '../../docker/jenkins/:/var/jenkins_home'
      - './etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'